name: Execute Code on Push

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  execute-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install langchain_community

      - name: Install Ollama
        run: |
          curl -sSL https://ollama.com/install.sh | bash

      - name: Start Ollama Service
        run: |
          nohup ollama serve > ollama.log 2>&1 &
          sleep 30  # Wait for Ollama to start up, adjust if necessary
          curl -I http://127.0.0.1:11434 || exit 1  # Check if Ollama is running

      - name: Execute Python script
        id: execute_code
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}  # Use your GitHub token stored as a secret
        run: python run_gemma.py

      - name: Add result to job summary
        if: always()  # Ensure this step runs even if previous steps fail
        run: |
          echo "## Execution Result" >> $GITHUB_STEP_SUMMARY
          
